package com.tsp.gespro.hibernate.pojo;
// Generated 10/09/2016 07:54:03 PM by Hibernate Tools 4.3.1



/**
 * CampoAdicionalProspectoValor generated by hbm2java
 */
public class CampoAdicionalProspectoValor  implements java.io.Serializable {


     private Integer idCampoAdicionalProspectoValor;
     private CampoAdicionalProspecto campoAdicionalProspecto;
     private String valor;
     private Integer idProspecto;

    public CampoAdicionalProspectoValor() {
    }

    public CampoAdicionalProspectoValor(CampoAdicionalProspecto campoAdicionalProspecto, String valor, Integer idProspecto) {
       this.campoAdicionalProspecto = campoAdicionalProspecto;
       this.valor = valor;
       this.idProspecto = idProspecto;
    }
   
    public Integer getIdCampoAdicionalProspectoValor() {
        return this.idCampoAdicionalProspectoValor;
    }
    
    public void setIdCampoAdicionalProspectoValor(Integer idCampoAdicionalProspectoValor) {
        this.idCampoAdicionalProspectoValor = idCampoAdicionalProspectoValor;
    }
    public CampoAdicionalProspecto getCampoAdicionalProspecto() {
        return this.campoAdicionalProspecto;
    }
    
    public void setCampoAdicionalProspecto(CampoAdicionalProspecto campoAdicionalProspecto) {
        this.campoAdicionalProspecto = campoAdicionalProspecto;
    }
    public String getValor() {
        return this.valor;
    }
    
    public void setValor(String valor) {
        this.valor = valor;
    }
    public Integer getIdProspecto() {
        return this.idProspecto;
    }
    
    public void setIdProspecto(Integer idProspecto) {
        this.idProspecto = idProspecto;
    }




}


