package com.tsp.gespro.hibernate.pojo;
// Generated 10/09/2016 07:54:03 PM by Hibernate Tools 4.3.1



/**
 * CampoAdicionalClienteValor generated by hbm2java
 */
public class CampoAdicionalClienteValor  implements java.io.Serializable {


     private Integer idCampoAdicionalClienteValor;
     private CampoAdicionalCliente campoAdicionalCliente;
     private String valor;
     private Integer idCliente;

    public CampoAdicionalClienteValor() {
    }

    public CampoAdicionalClienteValor(CampoAdicionalCliente campoAdicionalCliente, String valor, Integer idCliente) {
       this.campoAdicionalCliente = campoAdicionalCliente;
       this.valor = valor;
       this.idCliente = idCliente;
    }
   
    public Integer getIdCampoAdicionalClienteValor() {
        return this.idCampoAdicionalClienteValor;
    }
    
    public void setIdCampoAdicionalClienteValor(Integer idCampoAdicionalClienteValor) {
        this.idCampoAdicionalClienteValor = idCampoAdicionalClienteValor;
    }
    public CampoAdicionalCliente getCampoAdicionalCliente() {
        return this.campoAdicionalCliente;
    }
    
    public void setCampoAdicionalCliente(CampoAdicionalCliente campoAdicionalCliente) {
        this.campoAdicionalCliente = campoAdicionalCliente;
    }
    public String getValor() {
        return this.valor;
    }
    
    public void setValor(String valor) {
        this.valor = valor;
    }
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }




}


