package com.tsp.gespro.hibernate.pojo;
// Generated 10/09/2016 07:44:52 PM by Hibernate Tools 4.3.1



/**
 * ClientesClientes generated by hbm2java
 */
public class ClientesClientes  implements java.io.Serializable {


     private Integer id;
     private Integer clienteId;
     private Integer clienteSucursalId;

    public ClientesClientes() {
    }

    public ClientesClientes(Integer clienteId, Integer clienteSucursalId) {
       this.clienteId = clienteId;
       this.clienteSucursalId = clienteSucursalId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getClienteId() {
        return this.clienteId;
    }
    
    public void setClienteId(Integer clienteId) {
        this.clienteId = clienteId;
    }
    public Integer getClienteSucursalId() {
        return this.clienteSucursalId;
    }
    
    public void setClienteSucursalId(Integer clienteSucursalId) {
        this.clienteSucursalId = clienteSucursalId;
    }




}


