package com.tsp.gespro.hibernate.pojo;
// Generated 10/09/2016 07:51:30 PM by Hibernate Tools 4.3.1



/**
 * Coberturaproyecto generated by hbm2java
 */
public class Coberturaproyecto  implements java.io.Serializable {


     private Integer id;
     private int idCobertura;
     private int idProyecto;

    public Coberturaproyecto() {
    }

    public Coberturaproyecto(int idCobertura, int idProyecto) {
       this.idCobertura = idCobertura;
       this.idProyecto = idProyecto;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getIdCobertura() {
        return this.idCobertura;
    }
    
    public void setIdCobertura(int idCobertura) {
        this.idCobertura = idCobertura;
    }
    public int getIdProyecto() {
        return this.idProyecto;
    }
    
    public void setIdProyecto(int idProyecto) {
        this.idProyecto = idProyecto;
    }




}


