package com.tsp.gespro.hibernate.pojo;
// Generated 10/09/2016 08:04:13 PM by Hibernate Tools 4.3.1



/**
 * Promotorproyecto generated by hbm2java
 */
public class Promotorproyecto  implements java.io.Serializable {


     private Integer idPromotorproyecto;
     private int idUser;
     private int idProyecto;

    public Promotorproyecto() {
    }

    public Promotorproyecto(int idUser, int idProyecto) {
       this.idUser = idUser;
       this.idProyecto = idProyecto;
    }
   
    public Integer getIdPromotorproyecto() {
        return this.idPromotorproyecto;
    }
    
    public void setIdPromotorproyecto(Integer idPromotorproyecto) {
        this.idPromotorproyecto = idPromotorproyecto;
    }
    public int getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }
    public int getIdProyecto() {
        return this.idProyecto;
    }
    
    public void setIdProyecto(int idProyecto) {
        this.idProyecto = idProyecto;
    }




}


